DROP TABLE IF EXISTS UNITS;
DROP TABLE IF EXISTS ENEMIES;
DROP TABLE IF EXISTS PLAYER;
DROP TABLE IF EXISTS TRAITS;
DROP TABLE IF EXISTS PASSIVES;
DROP TABLE IF EXISTS ABILITIES;
DROP TABLE IF EXISTS TRIBES;
DROP TABLE IF EXISTS SPECIALS;
DROP TABLE IF EXISTS POSITION;



CREATE TABLE PLAYER (
    ID SERIAL PRIMARY KEY NOT NULL,
    HEALTH INTEGER NOT NULL,
    TYPES NOT NULL);

CREATE TABLE UNITS (
    ID SERIAL PRIMARY KEY NOT NULL, 
    NAME VARCHAR(30) NOT NULL, 
    HEALTH INTEGER NOT NULL,
    ENERGY INTEGER NOT NULL
    DAMAGE INTEGER NOT NULL,
    ATTACK_RANGE INTEGER NOT NULL,
    TRIBE_ID INT NOT NULL,
    TRAIT_ID INT NOT NULL,
    SPECIAL_ID INT NOT NULL,
    POSITION_ID INT NOT NULL);

CREATE TABLE ENEMIES (
    ID SERIAL PRIMARY KEY NOT NULL,
    NAME VARCHAR(30) NOT NULL,
    HEALTH INTEGER NOT NULL,
    DAMAGE INTEGER NOT NULL,
    ATTACK_RANGE INTEGER NOT NULL);

CREATE TABLE PASSIVES (
    ID SERIAL PRIMARY KEY NOT NULL,
    UNIT VARCHAR(20) NOT NULL,
    NAME VARCHAR(15) NOT NULL,
    DESCRIPTION VARCHAR(100) NOT NULL);
    
CREATE TABLE ABILITIES (
    ID SERIAL PRIMARY KEY NOT NULL,
    UNIT VARCHAR(20) NOT NULL,
    NAME VARCHAR(15) NOT NULL,
    DESCRIPTION VARCHAR(100) NOT NULL);

CREATE TABLE TRIBES (
    ID SERIAL PRIMARY KEY NOT NULL,
    NAME VARCHAR(15) NOT NULL,
    DESCRIPTION VARCHAR(100) NOT NULL,
    BUFF VARCHAR(30) NOT NULL);

CREATE TABLE TRAITS (
    ID SERIAL PRIMARY KEY NOT NULL,
    NAME VARCHAR(15) NOT NULL,
    DESCRIPTION VARCHAR(100) NOT NULL,
    BUFF VARCHAR(30) NOT NULL);

CREATE TABLE SPECIALS (
    ID SERIAL PRIMARY KEY NOT NULL,
    NAME VARCHAR(15) NOT NULL,
    DESCRIPTION VARCHAR(100) NOT NULL,
    BUFF VARCHAR(30) NOT NULL);

CREATE TABLE POSITION (
    ID SERIAL PRIMARY KEY NOT NULL,
    X_POS INTEGER NOT NULL,
    Y_POS INTEGER NOT NULL;
)

